### ISSUE TITLE
Why `sensors-sys`?

### ISSUE THREAD

**Issue by koutheir** [lupinx2/rs_coretemp#1]
Why are you using the crate `sensors-sys` instead of `lm-sensors` in this project? Is something missing from `lm-sensors`?

**Comment by lupinx2** [comment]
This was a learning project for myself, and my first time doing any kind of hardware interfacing. I am not aware of any technical advantages or disadvantages of either library against the other.  
``sensors-sys``  is already a Rust crate, and I was not experienced in using more than a single language for a project; so it seemed like it would be the easier choice for me.

**Comment by lupinx2** [comment]
This was a learning project for myself, and my first time doing any kind of hardware interfacing. I am not aware of any technical advantages or disadvantages of either library against the other.  
``sensors-sys``  is already a Rust crate; and I was not experienced in using more than a single language for a project, so it seemed like it would be the easier choice for me.

**Comment by koutheir** [comment]
Both `sensors-sys` and [`lm-sensors`](https://crates.io/crates/lm-sensors) are Rust crates, but they expose different abstractions. `lm-sensors` exposes a safer and more ergonomic interface, and `sensors-sys` exposes the raw API of `libsensors`. The `sensors-sys` crate is not intended to be used in most situations, so I was curious about your reasons to use it.
